SELECT distinct a.CODSTAN, b.NUMSTANZA, a.CODLETTO, a.NUMERO_LETTO, b.NUMLETTI
FROM GELETTI a, GESTANZE b
where a.CODSTAN = b.CODSTAN
--and a.CODSTAN = 121
and b.NUMSTANZA = 123
--and a.CODLETTO=23
order by 1, 2, 3, 4